### PR TITLE
added Largest_of_three_no in C

### PR DESCRIPTION
**Pull request by volt-l18**

### CODE REVIEW

**Comment by Dhruv031003** [comment]
@infinity-lightning 
In the C code, add condition for equal nos.

**Comment by infinity-lightning** [comment]
> @infinity-lightning In the C code, add condition for equal nos.

done

**Comment by Dhruv031003** [comment]
@infinity-lightning
You were not assigned the Cpp one. Please remove it.

**Review by alok-96 — COMMENTED** [review]
Please don't take input from yourself. Write code that takes input from the user.
And describe the else part more clearly like when the input will be invalid and when the values ​​will be same.

**Pull request closed without merging**
